---
kind: pipeline
type: docker
name: Ubuntu focal (amd64)

steps:
- name: build
  image: ubuntu:focal
  commands:
  - cat /etc/apt/apt.conf.d/proxy || echo "proxy not found"
  - ls -l /etc/drone || echo "no /etc/drone"
  - ls -l /cache || echo "no /cache"
  - apt-get update && apt-get install -y eatmydata
  - eatmydata apt-get dist-upgrade -y
  - eatmydata apt-get install -y cmake g++ git ninja-build libsodium-dev pkg-config libzmq3-dev
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake .. -G Ninja -DCMAKE_CXX_FLAGS=-fdiagnostics-color=always
  - ninja -v
  - ./tests/tests --use-colour yes

---
kind: pipeline
type: docker
name: Ubuntu bionic (amd64)

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - apt-get update && apt-get install -y eatmydata
  - eatmydata apt-get dist-upgrade -y
  - eatmydata apt-get install -y cmake g++ git ninja-build libsodium-dev pkg-config libzmq3-dev
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake .. -G Ninja -DCMAKE_CXX_FLAGS=-fdiagnostics-color=always
  - ninja -v
  - ./tests/tests --use-colour yes

---
kind: pipeline
type: docker
name: Debian sid (amd64)

steps:
- name: build
  image: debian:sid
  commands:
  - apt-get update && apt-get install -y eatmydata
  - eatmydata apt-get dist-upgrade -y
  - eatmydata apt-get install -y cmake g++ git ninja-build libsodium-dev pkg-config libzmq3-dev
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake .. -G Ninja -DCMAKE_CXX_FLAGS=-fdiagnostics-color=always
  - ninja -v
  - ./tests/tests --use-colour yes

---
kind: pipeline
type: docker
name: Debian buster (amd64)

steps:
- name: build
  image: debian:buster
  commands:
  - apt-get update && apt-get install -y eatmydata
  - eatmydata apt-get dist-upgrade -y
  - eatmydata apt-get install -y cmake g++ git ninja-build libsodium-dev pkg-config libzmq3-dev
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake .. -G Ninja -DCMAKE_CXX_FLAGS=-fdiagnostics-color=always
  - ninja -v
  - ./tests/tests --use-colour yes

---
kind: pipeline
type: docker
name: Ubuntu bionic (ARM64)

platform:
    arch: arm64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - cat /etc/apt/apt.conf.d/proxy || echo "proxy not found"
  - ls -l /etc/drone || echo "no /etc/drone"
  - ls -l /cache || echo "no /cache"
  - apt-get update && apt-get install -y eatmydata
  - eatmydata apt-get dist-upgrade -y
  - eatmydata apt-get install -y cmake g++ git ninja-build libsodium-dev pkg-config libzmq3-dev
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake .. -G Ninja -DCMAKE_CXX_FLAGS=-fdiagnostics-color=always
  - ninja -v
  - ./tests/tests --use-colour yes

---
kind: pipeline
type: docker
name: Debian sid (ARM 64)

platform:
    arch: arm64

steps:
- name: build
  image: debian:sid
  commands:
  - apt-get update && apt-get install -y eatmydata
  - eatmydata apt-get dist-upgrade -y
  - eatmydata apt-get install -y cmake g++ git ninja-build libsodium-dev pkg-config libzmq3-dev
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake .. -G Ninja -DCMAKE_CXX_FLAGS=-fdiagnostics-color=always
  - ninja -v
  - ./tests/tests --use-colour yes

---
kind: pipeline
type: docker
name: Debian buster (armhf)

platform:
    arch: arm

steps:
- name: build
  image: debian:sid
  commands:
  - apt-get update && apt-get install -y eatmydata
  - eatmydata apt-get dist-upgrade -y
  - eatmydata apt-get install -y cmake g++ git ninja-build libsodium-dev pkg-config libzmq3-dev
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake .. -G Ninja -DCMAKE_CXX_FLAGS=-fdiagnostics-color=always
  - ninja -v
  - ./tests/tests --use-colour yes
